services:
  app:
    build: node
    tty: true
    volumes:
      - .:/workspace:cached
      - ./node/app:/app
    ports:
      - "3000:3000"
      - "5555:5555"
  
  db:
    build: database
    volumes:
      - ./database/psdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_INITDB_ARGS: "${POSTGRES_INITDB_ARGS}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
