FROM node:22-alpine

ENV NODE_ENV=development

WORKDIR /app

RUN apk update && \
    apk add git && \
    apk add openssh && \
    apk add bash

RUN npm install -g express-generator

ENV HOST 0.0.0.0
EXPOSE 3000